;; Three blocks (A B and C) are on the table along with three sprayers
;; (red, green, blue), three paint cans (red, green, blue), a water
;; bucket and a clean brush.  Paint A, B and C red, blue and green,
;; respectively. End with the arm empty and the brush clean.

(define (problem 3)
  (:domain hw5)
  (:objects A B C D E F G H I J K )
  (:init (arm-empty)
          (block A)
	  (on-table A)
	  (clear A)
          (block B)
	  (on-table B)
	  (clear B)
          (block C)
	  (on-table C)
	  (clear C)
	  (sprayer D red)
	  (on-table D)
	  (clear D)
	  (sprayer E green)
	  (on-table E)
	  (clear E)
	  (sprayer F blue)
	  (on-table F)
	  (clear F)
	  (paint-can G red)
	  (on-table G)
	  (clear G)
	  (paint-can H green)
	  (on-table H)
	  (clear H)
	  (paint-can I blue)
	  (on-table I)
	  (clear I)
	  (water-bucket J)
	  (on-table J)
	  (clear J)
	  (brush K)
	  (on-table K)
	  (clear K)
	  (clean K))

(:goal (and (arm-empty)
  	 (color A red)
	 (color B green)
	 (color C blue)
	 (clean K))))